version: "3.7"
volumes:
  pg_data:
services:
  database:
    image: "postgres:latest"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "pg_data:/var/lib/postgres"
      #- "./backend/sql/postgres.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
      PG_DATABASE: "${PG_DATABASE}"
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_ROOT_PASSWORD: "${PG_PASSWORD}"
