name: Docker Backend

on:
  push:
    branches: [ main, dev ]
    paths: [ 'backend/**', '.github/workflows/docker-backend.yml' ]
  workflow_dispatch:

env:
  COMPONENT: backend

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write    
    strategy:
      matrix:
        build: ["release", "dev"]
    services:
      database:
        image: postgres:latest
        env:
          PG_DATABASE: waitlist
          PG_USER: waitlist
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_RANDOM_ROOT_PASSWORD: true
        ports:
          - 5432:5432

    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Build
        working-directory: ./backend
        run: docker build --network host --build-arg "PROFILE=${{ matrix.build }}" --build-arg "DATABASE_PASSWORD=${{ secrets.PG_PASSWORD }}" -t $COMPONENT .

      - name: Docker Push
        run: |
          IMAGE_URL=ghcr.io/${{ github.repository }}
          IMAGE_URL=$(echo $IMAGE_URL | tr '[A-Z]' '[a-z]')
          
          # Strip "v" prefix from tag name
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest
          [ "${{ matrix.build }}" == "dev" ] && VERSION="${VERSION}-debug"

          docker tag $COMPONENT $IMAGE_URL-$COMPONENT:$VERSION
          docker push $IMAGE_URL-$COMPONENT:$VERSION
